### ISSUE TITLE
Instructions: Remove Unnecessary Continues

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1047]
Currently we have unnecessary continues in the instructions, here are some samples:

https://graphhopper.com/maps/?point=48.004367%2C8.137822&point=48.003878%2C8.137844
https://graphhopper.com/maps/?point=48.177999%2C8.572013&point=48.17788%2C8.573037

Currently, we are creating an instruction if we are not sure if an instruction is needed at this point. With the current data it's very complicated to improve the current situation. With highway information we should be able to improve it.

If we are continuing on the same highway class but the outgoing edge is a different highway class, then it is very likely that the turn instruction is not necessary.

Related to #990

**Comment by boldtrn** [comment]
Should be fixed with #1844

**Comment by karussell** [comment]
#1844 has improved the situation a lot but unfortunately the two examples above are not yet fixed. Also [I found an instruction](https://graphhopper.com/maps/?point=51.367105%2C14.491246&point=51.369048%2C14.483092) which is now removed but important because "follow the road" is a "right turn".

**Comment by boldtrn** [comment]
Thanks for the pointer. I will have a look and see if we can improve the situation :+1:

**Comment by boldtrn** [comment]
> the two examples above are not yet fixed

If you disable turn_costs they are fixed, I just created an issue for this #1883

**Comment by karussell** [comment]
Ah, ups. This is indeed also a deployment problem (see #1883). Sorry for the bubble.
