### ISSUE TITLE
racing bike router not sticking to path

### ISSUE THREAD

**Issue by jguddas** [graphhopper/graphhopper#2357]
**Describe the bug**
The racing bike router behaves like a path does not exist.

**To Reproduce**
![image](https://user-images.githubusercontent.com/25524993/124400311-bd07db00-dd21-11eb-9fe6-976a112fdde0.png)
https://graphhopper.com/maps/?point=52.3737%2C9.716227&point=52.371181%2C9.718657&point=52.366035%2C9.721806&locale=en-us&elevation=false&profile=racingbike&use_miles=false&selected_detail=Elevation&layer=Omniscale

**Expected behavior**

To in this instance behave like the normal bike router and consider the path.

![image](https://user-images.githubusercontent.com/25524993/124400319-cdb85100-dd21-11eb-9a43-729c87aba9ed.png)
https://graphhopper.com/maps/?point=52.3737%2C9.716227&point=52.371181%2C9.718657&point=52.366035%2C9.721806&locale=en-us&elevation=false&profile=bike&use_miles=false&selected_detail=Elevation&layer=Omniscale

**Comment by ratrun** [comment]
The race bike profile avoids `sac_scale=hiking` in any case. 
See
https://github.com/graphhopper/graphhopper/blob/e69213853be8b5fa224805850133e1f6c20f8bb6/core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java#L154-L156
I doubt that this tagging is correct.

**Comment by karussell** [comment]
This seems to be a tagging issue. Closing for now.

**Comment by ratrun** [comment]
Looking at taginfo https://taginfo.openstreetmap.org/tags/sac_scale=hiking#combinations and overpass queries there are all kinds of combinations, which do not make sense but are still frequently used even in rural areas. Frequent examples are `sac_scale=hiking` toghether with `highway=residential` or `tracktype=grade1` or  `surface=asphalt` ....
As we cannot say that all of these usages are tagging errors I came to the conclusion that the currecnt implementation seems too strict and it would be better to allow `sac_scale=hiking` for the race bike profile. What do you think?

**Comment by jguddas** [comment]
>  I came to the conclusion that the currecnt implementation seems too strict and it would be better to allow sac_scale=hiking for the race bike profile.

I agree.

Thanks to your help, I have realized that this isn't the first time I have had this issue.

I have fixed these issues in my local area with this overpass query https://overpass-turbo.eu/s/198V

**Comment by karussell** [comment]
I'm still not convinced that this isn't a tagging issue: https://www.mapillary.com/app/?lat=52.371444640688&lng=9.7183859746964&z=17&pKey=769323700616733&focus=photo

**Comment by ratrun** [comment]
> But under certain conditions we could ignore the sac_scale value, yes.

I would just allow `sac_scale=hiking` for race bike. The PR is trivial, I am going to prepare it.
