### ISSUE TITLE
vehicle=destination should be preferred over access=private

### ISSUE THREAD

**Issue by spixi** [graphhopper/graphhopper#3157]
**Describe the bug**
A bicyle road in Germany is usually tagged with "highway=unclassified", "bicycle=designated" and "vehicle=destination". In that case, the algorithm tries to avoid that bicycle road and wants to use private parking side-lanes ("highway=service", "access=private").

**To Reproduce**
https://graphhopper.com/maps/?point=48.312076%2C11.913495_Am+Stadion%2C+85435+Erding%2C+Bayern%2C+Deutschland&point=48.314453%2C11.912604_Volksfestplatz%2C+Sch%C3%BCtzenstra%C3%9Fe%2C+85435+Erding%2C+Bayern%2C+Deutschland&profile=car&layer=Omniscale
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=48.312285%2C11.913536%3B48.315004%2C11.911594#map=18/48.313707/11.914201

**Expected behavior**
The detour over the parking side-lanes should be avoided. Instead the direct way should be preferred.

**Screenshots & Logs**
![Image](https://github.com/user-attachments/assets/ff86bb81-362c-44a4-a3b5-7dca960a8420)
![Image](https://github.com/user-attachments/assets/38d42998-75e9-47ed-b03e-79d057514775)
![Image](https://github.com/user-attachments/assets/3ca306ec-f1d7-4a24-8613-b17e3487f66b)

**Comment by otbutz** [comment]
Please, don't do this:

![Image](https://github.com/user-attachments/assets/6ac45353-8f0d-4a76-a35a-462daeb8c70d)

[Tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer) is frowned upon in the OSM community.

**Comment by spixi** [comment]
> Please, don't do this:
> 
> ![Image](https://github.com/user-attachments/assets/6ac45353-8f0d-4a76-a35a-462daeb8c70d)
> 
> [Tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer) is frowned upon in the OSM community.

You propably mean [Tagging for the router"](https://wiki.openstreetmap.org/wiki/Tagging_for_the_router), but how can I avoid this?

**Comment by otbutz** [comment]
This is something that should be fixed in GraphHopper and not in the OSM dataset. The previous tagging was correct as far as I can see. You should revert your changeset.

**Comment by ratrun** [comment]
The title of this issue is not correct any longer as the detected detours are not tagged as `access=private` any more. But the problem still exists. It cannot be easily solved via changing the priority assignment in  the `car.json` custom model.
The issue is that if an edge can only be reached via other edges tagged as `vehicle=destination`, such an edge should inherit its `road_access=destination` encoded value from the `vehicle=destination` edge leading to it. So the title might be changed maybe into "Edges reachable via road_access=destination edges only should inherit the road_access value from its feeder edge".
I think that this issue is a duplicate of #733.
