### ISSUE TITLE
Routing over ferries that use the same nodes for intersection can cause impossible routes

### ISSUE THREAD

**Issue by mihai-craciun-ursu** [graphhopper/graphhopper#3238]
**Describe the bug**

Planning a route that contains a ferry path that intersect with another ferry path, both of them having a common OSM node causes routing to consider swapping between ferries mid cruise.

**To Reproduce**

Generate a route starting in the ferry boarding area of Hirtshals, Denmark and ending somewhere outside of it with an index prior to this date (5.10.2025)

Keep in consideration that this bug is reproducible because of an error in OSM blocking any exit from the boarding area that was fixed on request (Node [3436893358](https://www.openstreetmap.org/node/3436893358) and Node [5223427633](https://www.openstreetmap.org/node/5223427633) had access=no tag prior to this date)

OSM Ways involved in this issue

[61215714](https://www.openstreetmap.org/way/61215714)
[1265144048](https://www.openstreetmap.org/way/1265144048)
[230310229](https://www.openstreetmap.org/way/230310229)

**Expected behavior**

Switching between ferry ways should not be possible

**Screenshots & Logs**

[Graphhopper Maps](https://graphhopper.com/maps/?point=57.595534%2C9.977222&point=57.593471%2C9.98862&profile=car&layer=Omniscale)

<img width="1907" height="979" alt="Image" src="https://github.com/user-attachments/assets/18b8f62f-5420-4d3b-9edc-42a796e9f5ab" />

<img width="1907" height="979" alt="Image" src="https://github.com/user-attachments/assets/ffd06f4f-9135-47b5-8225-e9db2963b403" />

**Comment by karussell** [comment]
The problem that this comes to the surface is just that there is a barrier: https://www.openstreetmap.org/node/3436893358 which was fixed recently and we'll probably consider this fix in about 2-4 days.

**Comment by mihai-craciun-ursu** [comment]
Yes, as I mentioned above, the bug is vissible because of that barrier. But the issue of routing being able to hop from one ferry way to another still exists. If I were to create a custom profile that for example would prioritise ferry ways I would be able to take the ferries as seen in the route I appended regardless of that barrier.

**Comment by aritozen** [comment]
A simple example is [this](https://graphhopper.com/maps/?point=57.595534%2C9.977222&point=58.021755%2C8.041859&point=58.919824%2C5.583601&profile=foot&layer=Omniscale) from Hirtshals to Stavanger, which uses foot routing to force the ferry and then marks an extra stop to force the detour via Kristiansand. The extra stop wouldn't be necessary if there wasn't a direct route between Hirtshals and Stavanger.
In fact, the detour seems to exist sometimes in the year, according to OSM comment: https://www.openstreetmap.org/way/1265144048

This can only be solved in Graphhopper by treating the ways between stops as a single logical way. That would actually disqualify above route because the ferry from Kristiansand to Stavanger doesn't have a route relation.
Solving this issue might mean rethinking how ferries are treated, to be more like public transit instead of roads. The fact that ferry routing works at all right now is because the ways are connected to roads at their endpoints and usually don't share nodes with each other (thus making it a single logical way).

I will also note the [Wiki article](https://wiki.openstreetmap.org/wiki/Tag:route%3Dferry):

> The ferry route must not branch in the water, so the route must always be drawn to the ferry dock. This is important for routing to work correctly.

This is probably the simplest approach. Separate the overlapping ways. They aren't physically connected, so they shouldn't be logically connected.

**Comment by mihai-craciun-ursu** [comment]
Thank you for the better example. Unfortunately  from what I know there are ferry ways that are actually branching in OSM without connecting to ports, rather just being a connection to another ferry. Take for example the port of Calais, ferry that leads to Dover.
The way [1091284133](https://www.openstreetmap.org/way/1091284133) is a branch of [209213884](https://www.openstreetmap.org/way/209213884) without being able to reach anything else other than a node of the main way on its own

**Comment by aritozen** [comment]
In the Dover - Calais case is that actually a problem? The only reason to route over the ferries would be to go to Dover, so no (at least somewhat reasonable) route should insert a magic transfer out on the water, from what I can tell.

**Comment by karussell** [comment]
> But the issue of routing being able to hop from one ferry way to another still exists.

The problem is that the ferries are tagged like a street network and so [other routers have this problem too](https://valhalla.openstreetmap.de/directions?profile=car&style=carto&wps=9.989831%2C57.5924552%2C7.678076752868918%2C57.81937064988264).

For car it could be fixed if a turn restriction is added :) ... but I'm unsure if it is relevant for real world cases (except for tagging issues or unusual starting points). Do you have any real world routing issues coming from this limitation?

**Comment by karussell** [comment]
For now closing as not planned...
