### ISSUE TITLE
JS calculates route when deleting point

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#613]
I just saw that we cannot add points anymore (this is fixed in #612).

When you add one point and delete one point, a route request with two undefined points is sent.

**Comment by karussell** [comment]
So these are two issues where the first one is already fixed? (thanks again!)

**Comment by boldtrn** [comment]
Yes, but I didn't want to create a seperate issue for #612 .

**Comment by karussell** [comment]
I see, hmmh we need a better testing structure here. Refactoring should be done without fear.

**Comment by karussell** [comment]
It looks like after #615 this is also fixed here. Can you confirm this?

**Comment by boldtrn** [comment]
I can still reproduce this error using the current master. This is even possible on the deployed version: https://graphhopper.com/maps/?point=undefined&point=undefined&locale=de-DE&vehicle=car&weighting=fastest&elevation=true&layer=Omniscale

Just goto https://graphhopper.com/maps/.
Click the plus.
Remove one point.
It will route from undefined to undefined.

**Comment by karussell** [comment]
That existed before the refactoring and is a dup #272 IMO (?)

**Comment by boldtrn** [comment]
Yes you are right. Haven't found that issue, because I thought it was introduced in the refactoring. Will close it, since this is a duplicate.
