### ISSUE TITLE
Route API returns 'null' when two points with same coordinates are given

### ISSUE THREAD

**Issue by edy** [graphhopper/graphhopper#840]
The following URL returns a `null` on my graphhopper installation (tested with 0.7 and 0.8 snapshot (graphhopper-web-0.8-20161004.180136-82-bin.zip)):
```
/route?point=51.716819%2C8.745117&point=51.716819%2C8.745117&point=52.008555%2C8.513031&type=json&key=&locale=de-DE&vehicle=car&weighting=fastest&elevation=false&use_miles=false
```

[see my 0.8 installation here](http://dev02.loom-technologies.com:8991/route?point=51.730591%2C8.703121&point=51.730591%2C8.703121&point=51.869232%2C8.655377&type=json&key=&locale=de-DE&vehicle=car&weighting=fastest&elevation=false)

This workes fine on the official [graphhopper demo](https://graphhopper.com/maps/?point=51.716819%2C8.745117&point=51.716819%2C8.745117&point=52.008555%2C8.513031&locale=de-DE&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) too.

Log:
```
2016-10-18 15:06:36,142 [qtp910091170-15] INFO  com.graphhopper.http.GHBaseServlet - point=51.716819%2C8.745117&point=51.716819%2C8.745117&point=52.008555%2C8.513031&type=json&key=&locale=de-DE&vehicle=car&weighting=fastest&elevation=false&use_miles=false 172.17.0.1 de_DE Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 [51.716819,8.745117, 51.716819,8.745117, 52.008555,8.513031], took:0.00431475, , fastest, car, alternatives: 1, distance0: 45218.74921401323, time0: 30min, points0: 418, debugInfo: tmode:NODE_BASED; idLookup:0.002189374s; , algoInit:1.9797E-5s, dijkstrabiCH-routing:9.966E-6s, extract time:5.13E-7;, algoInit:9.69E-6s, dijkstrabiCH-routing:7.82693E-4s, extract time:6.3767E-5;, algoInit:1.9797E-5s, dijkstrabiCH-routing:9.966E-6s, extract time:5.13E-7;, algoInit:9.69E-6s, dijkstrabiCH-routing:7.82693E-4s, extract time:6.3767E-5, simplify (593->418)
```

**Comment by karussell** [comment]
It could be an issue that we have already fixed. What is the stacktrace you get on the server side?

**Comment by edy** [comment]
i don't get any exceptions

**Comment by karussell** [comment]
This is strange and looks like a bug. A similar one was fixed recently #788 

Can you try with the [recent release build](https://oss.sonatype.org/content/groups/public/com/graphhopper/graphhopper-web/0.8.0/graphhopper-web-0.8.0-bin.zip), but clean the graphhopper folder before a new import is done?

If the problem persists I'll try with a small area extract and [this shorter route](http://dev02.loom-technologies.com:8991/route?point=51.716819%2C8.745117&point=51.716819%2C8.745117&point=51.717856%2C8.745246&type=json&key=&locale=de-DE&vehicle=car&weighting=fastest&elevation=false) (still failing)

**Comment by edy** [comment]
i cleaned the folder and deployed the 0.8 release build, but still get a null result. 
i am using this pbf file: http://download.geofabrik.de/europe/germany/nordrhein-westfalen/detmold-regbez.html

**Comment by boldtrn** [comment]
@edy Have you tried with the nordrhein-westfalen.osm.pbf? I had issues with the regbez extracts of geofabrik some time ago. I don't remember the exact problem, but I remember that I used the bigger extract for some reason.

**Comment by edy** [comment]
yep, still a null response. same with europe

**Comment by karussell** [comment]
Can reproduce this issue and looks very strange. The created HashMap is okay but then JsonObject(map).toString returns "nulls" for some reason.

**Comment by karussell** [comment]
Wow, what an ugly catching code from json.org

```java
try { return this.toString(0); } catch (Exception e) { return null; }
```
And the exception is: 'org.json.JSONException: JSON does not allow non-finite numbers.'

To avoid this catching we must not call the generic toString() and e.g. use toString(0) directly. Will fix this and the underlying problem.

**Comment by karussell** [comment]
Can you confirm that my fix works for you too?

**Comment by edy** [comment]
It works. Thank you very much!

**Comment by karussell** [comment]
Should be released soonish as 0.8.1, see announcement [here](https://graphhopper.com/blog/2016/10/18/graphhopper-routing-engine-0-8-released/).
